bookreadersapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('webapp.urls_api', namespace='apiapp')),
    path('', include('webapp.urls', namespace='webapp'))
]

webapp/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = 'webapp'

urlpatterns = [
    path('api/readinglist', auth_views.login_required(
            views.BookListApiView.as_view()), name='api-reading-list'),
    path('api/edit-book-<int:pk>', auth_views.login_required(
            views.BookUpdateApiView.as_view()), name='api-reading-detail'),
    path('login/', auth_views.LoginView.as_view(
            redirect_authenticated_user=True,
            template_name='webapp/login.html',
            success_url=reverse_lazy('webapp:books_listing')),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='webapp/logout.html'
    ), name='logout'),
    path('add/', auth_views.login_required(views.BookAddView.as_view()),
         name='book-add'),
    path('delete-book-<int:pk>',
         auth_views.login_required(views.BookDeleteView.as_view()),
         name='book-delete'),
    path('edit-book-<int:pk>',
         auth_views.login_required(views.BookEditView.as_view()),
         name='book-edit'),
    path('', auth_views.login_required(views.BooksListView.as_view()),
         name='books_listing')
]

webapp/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

STATUS_CHOICES = [
    ('To Read', 'To Read'),
    ('Reading', 'Reading'),
    ('Completed', 'Completed')
]


class BookModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book_name = models.CharField(max_length=255, blank=False)
    author_name = models.CharField(max_length=255, blank=False)
    publication = models.CharField(max_length=255, blank=False)
    year_of_publication = models.PositiveIntegerField(
                                default=datetime.today().year)
    summary = models.TextField(max_length=2500, blank=False)
    status = models.CharField(max_length=25, choices=STATUS_CHOICES)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % (self.book_name)

    class Meta:
        verbose_name = 'Book'
        verbose_name_plural = 'Books'

webapp/forms.py
from django import forms
from django.apps import apps
BookModel = apps.get_model('webapp', 'BookModel')


class AddBookForm(forms.ModelForm):
    class Meta:
        model = BookModel
        fields = ['book_name', 'author_name', 'publication',
                  'year_of_publication', 'summary', 'status']

webapp/views.py
from django.views import generic
from django.apps import apps
from django.urls import reverse_lazy
from django.http import Http404
from . import forms
from rest_framework import generics
from .serializers import BookModelSerializer

BookModel = apps.get_model('webapp', 'BookModel')

# Web Views Start


class BooksListView(generic.ListView):
    '''
        Reading List View returns the list of books created by the logedin user
    '''
    template_name = 'webapp/book_list.html'
    model = BookModel
    context_object_name = 'books_list'

    def get_queryset(self):
        queryset = super(BooksListView, self).get_queryset()
        # Filters the queryset based on the GET request
        if 'filterby' in self.request.GET:
            queryset = queryset.filter(user=self.request.user)
            if self.request.GET['filterby'] == 'All':
                return queryset
            return queryset.filter(status=self.request.GET['filterby'])
        queryset = queryset.filter(user=self.request.user)
        return queryset


class BookAddView(generic.CreateView):
    '''
        Book Add view is used to add the book to readinglist
    '''
    template_name = 'webapp/add_book.html'
    # CreatView using formclass
    form_class = forms.AddBookForm
    success_url = reverse_lazy('webapp:books_listing')

    def form_valid(self, form):
        # adds the user as currently logedin user
        form.instance.user = self.request.user
        return super().form_valid(form)


class BookEditView(generic.UpdateView):
    '''
        Book Edit view is used to edit the information of already added book.
    '''
    template_name = 'webapp/edit_book.html'
    # UpdateView using model and fields
    model = BookModel
    fields = ['book_name', 'author_name', 'publication',
              'year_of_publication', 'summary', 'status']
    success_url = reverse_lazy('webapp:books_listing')


class BookDeleteView(generic.DeleteView):
    template_name = 'webapp/delete_book.html'
    model = BookModel
    success_url = reverse_lazy('webapp:books_listing')

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        # Checks wether currently logedin users book is only deleted or not
        if not obj.user == self.request.user:
            raise Http404('You are not allowed to delete this object')
        return obj

#  Web Views End

# Api Views Start


class BookListApiView(generics.ListCreateAPIView):
    serializer_class = BookModelSerializer

    def get_queryset(self):
        return BookModel.objects.filter(user=self.request.user)


class BookUpdateApiView(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = BookModelSerializer

    def get_queryset(self):
        return BookModel.objects.filter(user=self.request.user)

#  Api Views End

assets/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <title>Book Reader's App</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block stylesheet %}
    {% endblock %}
  </head>
  <body>
    {% block header %}{% endblock  %}
    {% block content %}{% endblock  %}
    {% block footer %}{% endblock  %}
    {% block scripts %}
      <script type="text/javascript" src="{% static 'jquery/js/jquery-3.3.1.min.js' %}">
      </script>
      <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}">
      </script>
      <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js">
      </script>
      <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

      {% block page_specific_script %}{% endblock %}
    {% endblock %}
  </body>
</html>

assets/templates/layout.html
{% extends "base.html" %}
{% block header %}
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'webapp:books_listing' %}">Book Readers App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  {% if request.user.is_authenticated %}
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'webapp:book-add' %}">Add a book <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:books_listing' %}">View all books</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'apiapp:api-reading-list' %}">Api</a>
      </li>
    </ul>
  </div>
  <a class="navbar btn btn-primary" href="{% url 'webapp:logout' %}">Logout</a>
  {% endif %}
</nav>
{% endblock %}

assets/templates/webapp/add_book.html
{% extends "layout.html" %}
{% load widget_tweaks %}


{% block content %}
<div class="container">
  <h1 class="mt-3">Add a new book</h1>
  <form class="mt-3" action="" method="post">
    {% csrf_token %}
    <div class="form-group">
      <div class="row">
        <div class="col-md-6">
          {% render_field form.book_name class='form-control' placeholder='Book name'%}
        </div>
        {{form.book_name.errors}}
        <div class="col-md-6">
          {% render_field form.author_name class='form-control' placeholder='Author name'%}
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-md-6">
          {% render_field form.publication class='form-control' placeholder='Publication name'%}
        </div>
        <div class="col-md-6">
          {% render_field form.year_of_publication class='form-control' placeholder='Author name'%}
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-md-6">
          {% render_field form.summary class='form-control' placeholder='Summary'%}
        </div>
        <div class="col-md-6">
          {% render_field form.status class='form-control' %}
        </div>
      </div>
    </div>
    <button type="submit" class="btn btn-primary" name="button">Add the book</button>
  </form>
</div>
{% endblock %}

assets/templates/webapp/book_list.html
{% extends "layout.html" %}

{% block page_specific_script %}
  <script type="text/javascript">
  $(document).ready(function() {
    $('#readingList').DataTable();
  });
  $('form select').on('change', function(){
    var value = $(this).val();
    if (value!='--------'){
      $(this).closest('form').submit();
    }
  });
  </script>
{% endblock %}

{% block content %}
<div class="container-fluid">
  <h1>Reading List</h1>
  <form  method="get">
    <div class="form-group col-md-1">
       <label for="filterByStatus">Filter By Status</label>
       <select name='filterby' class="form-control" id="filterByStatus" >
         <option value="--------">----------</option>
         <option value="All" {% if request.GET.filterby == 'All' %} selected {% endif %}>All</option>
         <option value="To Read" {% if request.GET.filterby == 'To Read' %} selected {% endif %}>To Read</option>
         <option value="Reading" {% if request.GET.filterby == 'Reading' %} selected {% endif %}>Reading</option>
         <option value="Completed" {% if request.GET.filterby == 'Completed' %} selected {% endif %}>Completed</option>
       </select>
     </div>
  </form>
  <table id="readingList" class="table table-striped table-bordered" style="width:100%">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Book Name</th>
        <th scope="col">Author Name</th>
        <th scope="col">Publication</th>
        <th scope="col">Publication Year</th>
        <th scope="col">Summary</th>
        <th scope="col">Status</th>
        <th scope="col">Created</th>
        <th scope="col">Updated</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for book_object in books_list %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{book_object.book_name}}</td>
        <td>{{book_object.author_name}}</td>
        <td>{{book_object.publication}}</td>
        <td>{{book_object.year_of_publication}}</td>
        <td>{{book_object.summary}}</td>
        <td>{{book_object.status}}</td>
        <td>{{book_object.created_on}}</td>
        <td>{{book_object.updated_on}}</td>
        <td>
          <a href="{% url 'webapp:book-edit' pk=book_object.id %}">Edit</a>
          <a href="{% url 'webapp:book-delete' pk=book_object.id %}">Delete</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

assets/templates/webapp/delete_book.html
{% extends "layout.html" %}

{% block content %}
  <div class="container mt-5">
    <p>Are you sure you want to delete the book <b>{{object}}</b> ?</p>
    <form class="" action="" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger" name="button">Delete</button>
      <a href="{% url 'webapp:books_listing' %}" class="btn btn-primary">No</a>
    </form>
  </div>
{% endblock %}

assets/templates/webapp/edit_book.html
{% extends "layout.html" %}
{% load widget_tweaks %}


{% block content %}
<div class="container">
  <h1 class="mt-3">Add a new book</h1>
  <form class="mt-3" action="" method="post">
    {% csrf_token %}
    <div class="form-group">
      <div class="row">
        <div class="col-md-6">
          {% render_field form.book_name class='form-control' placeholder='Book name'%}
        </div>
        <div class="col-md-6">
          {% render_field form.author_name class='form-control' placeholder='Author name'%}
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-md-6">
          {% render_field form.publication class='form-control' placeholder='Publication name'%}
        </div>
        <div class="col-md-6">
          {% render_field form.year_of_publication class='form-control' placeholder='Author name'%}
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-md-6">
          {% render_field form.summary class='form-control' placeholder='Summary'%}
        </div>
        <div class="col-md-6">
          {% render_field form.status class='form-control' %}
        </div>
      </div>
    </div>
    <button type="submit" class="btn btn-primary" name="button">Save</button>
  </form>
</div>
{% endblock %}

assets/templates/webapp/login.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
  {% if not request.user.is_authenticated %}
    <div class="container" >
        <div class="row justify-content-center align-items-center " style="height:80vh;">
            <div class="col-sm-6 p-5 pannel" >
                <h3 class="text-center ">Book Reader's App-Login</h3>
                <hr>
                {% if form.is_bound and not form.is_valid %}
                    <div class="alert alert-danger">
                        <strong>Please check the error messages below and try again</strong>
                    </div>
                {% endif %}
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <i class="icon-exclamation-sign"></i> {{ error }}
                        </div>
                    {% endfor %}
                {% endif %}
                <form class="" action="." method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {% render_field  form.username class="form-control username" placeholder="Enter your Email"%}
                    </div>
                    <div class="form-group">
                        {% render_field form.password class="form-control password" placeholder="Enter your Password"%}
                    </div>
                    <button type="submit" class="col-sm-12 btn submit" name="button">SUBMIT</button>
                </form>
            </div>
        </div>
    </div>
  {% endif %}
{% endblock %}

assets/templates/webapp/logout.html
{% extends "layout.html" %}

{% block content %}
  <div class="container-fluid mt-5">
    <h1>Logged out</h1>
    <p>Thanks for spending some quality time on the Web site today.</p>
  </div>
  <script type="text/javascript">
  setTimeout(function(){
      window.location.href = "/login/"
    }, 3000);
  </script>
{% endblock %}